export const TESLA_AUTHORIZE_URL = "https://auth.tesla.com/oauth2/v3/authorize"
export const TESLA_AUTHORIZE_TOKEN_URL = "https://auth.tesla.com/oauth2/v3/token"
export const TESLA_PARTNER_ACCOUNTS_URL = "https://fleet-api.prd.na.vn.cloud.tesla.com/api/1/partner_accounts"
export const TESLA_TOKEN_URL = "https://fleet-auth.prd.vn.cloud.tesla.com/oauth2/v3/token"
export const TESLA_AUDIENCE_URL = "https://fleet-api.prd.na.vn.cloud.tesla.com"
